Replace NextAuth with react-oidc-context
mlhmz/family-task-tracking pull request #98
Opened 2023-09-28 19:06 UTC by mlhmz

2023-09-28 19:44 UTC, mlhmz commented
Auth selbst und Error Handling ist soweit cool geworden.

Das Token Request Handling ist noch etwas weird, gucke mit einem useEffect ob ein Token entstanden ist und wenn ja pack ich den in einen Cookie.

Beim react-oidc-context wird nämlich der Token in den Session Storage gespeichert.

2023-09-28 19:44 UTC, mlhmz commented
Um den Keycloak URL sowie die Client-ID zu bekommen mache ich einen Server-Call ans Backend und blocke währenddessen die UI, bin mir da auch nicht sicher, ob das dann doch noch besser geht.

2023-09-29 10:07 UTC, marklse568 requested changes
hdl

2023-09-29 10:07 UTC, marklse568 commented on frontend/app/providers.tsx
> +};
```suggestion
const oidcConfig = {
  authority: process.env.KEYCLOAK_ISSUER ?? "",
  client_id: process.env.KEYCLOAK_CLIENT_ID ?? "",
  redirect_uri: "/",
} satisfies AuthProviderProps;
```

2023-09-29 10:08 UTC, marklse568 approved these changes
stabibi

2023-09-29 10:09 UTC, merged